# Use the official NGINX image as the base image
FROM nginx

# Copy the index.html file to the NGINX HTML directory
COPY index.html /usr/share/nginx/html

# Expose port 80 (the default port for NGINX)
EXPOSE 80